canal:
  client:
    instances:
      example:
        host: 192.168.200.128
        batchSize: 1000
        port: 11111
spring:
  rabbitmq:
    host: 192.168.200.128
    username: guest
    password: guest
    port: 5672