server:
  port: 9096
spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "http://localhost:8099" #跨域处理
            allowCredentials: true
            allowedMethods: #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      #登录微服务
      routes:
        - id: changgou_login
          uri: lb://login-service
          predicates:
            - Path=/api/changgou/**
          filters:
            - StripPrefix= 1
      #认证微服务
        - id: changgou_oauth_user
          uri: lb://user-auth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix= 1
      #用户微服务
        - id: changgou_user
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**
          filters:
            - StripPrefix= 1
      #购物车/订单微服务
        - id: changgou_cart
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/order/**
          filters:
              - StripPrefix= 1
      #购物车渲染服务
        - id: cart
          uri: lb://order-web
          predicates:
            - Path=/api/wcart/**,/api/worder/**,/api/wwxpay/**
          filters:
            - StripPrefix= 1
      #商品秒杀服务
        - id: seckill
          uri: lb://secKill
          predicates:
            - Path=/api/secKill/**
          filters:
            - StripPrefix= 1
      #商品秒杀渲染服务
        - id: seckill
          uri: lb://secKill-web
          predicates:
            - Path=/api/wsecKill/**
          filters:
            - StripPrefix= 1
  redis:
    host: 192.168.200.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true