server:
  port: 9001
spring:
  application:
    name: pay
  rabbitmq:
    port: 5672
    host: 192.168.200.128
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
pay:
  notifyUri: http://wrhhhhh.cross.echosite.cn/wxpay/notice

