spring:
  application:
    name: file-service
  servlet:
    multipart:
      #单个文件上传的大小
      max-file-size: 10MB
      #总上传文件的大小
      max-request-size: 10MB

server:
  port: 9099
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true